### ISSUE TITLE
Calculator is off recently

### ISSUE THREAD

**Issue by jch9678** [karldiab/EthereumMiningCalculator#2]
Usually your calculator perfectly reflects what I earn mining.  The last 2 days it is off.  I noticed you updated it 8 hours ago, does some time need to pass for it "to catch up"?

**Comment by karldiab** [comment]
Hey there,

Indeed you are right, it was off after the Homestead fork. The lowered block time made it inaccurate. I have since modified the logic to account for this. Try refreshing the calculator, the old logic is probably cached in your browser.

That being said, even with the alteration, the calculator is still slightly too optimistic (by about 4%) but I'll be fixing that in the next couple of hours. So remember to keep refreshing your browser!
